### ISSUE TITLE
1

### ISSUE THREAD

**Issue by SnowyRinlya** [ShirokoLEET/betternaven#1]
why dont you add me to your repository:(

**Comment by ShirokoLEET** [comment]
Eines Tages war Arnold auf Sendung, als ihn plötzlich jemand fragte: „Arnold, warum ist dein Kopf spitz?“ Arnold antwortete: „Dann frage ich Sie, sind Sie männlich oder weiblich? Wenn Sie eine Frau sind und so etwas sagen, ah, dann frage ich Sie, wenn Sie ein Mädchen sind, dann frage ich Sie, ist dann Ihr Kopf nicht spitz? Also ich frage dich, ist der Scheitel deines Kopfes spitz? Oder kahl, ah, oder, ah, gelb gefärbt, rot gefärbt, dann frage ich dich, ah, oder trägst du eine Perücke, wenn ja, wenn du ein Mann bist, dann frage ich dich, ah, du hast gesagt, mein Kopf ist spitz, dann frage ich dich, hast du dann eine Glatze? Hast du eine Glatze? Ah? Hast du eine Glatze oder hast du Haare, hm? Ich frage dich, was stimmt nicht mit meinem spitzen Kopf? Was stimmt nicht mit meinem spitzen Kopf? Hey, was stimmt nicht mit meinem spitzen Kopf? Was stimmt nicht mit meinem spitzen Kopf? Was stimmt nicht mit meinem Scheitel? Was stimmt nicht mit meinem Scheitel? Ich bin nur spitz, ich will nur spitz sein, was stimmt damit nicht, ah, du bist nicht daran gewöhnt, ah.“

Übersetzt mit DeepL.com (kostenlose Version)
